/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'GenerateAchievements': EventHandler<{ username: string; year: number }, { topic: 'finalize-wrapped'; data: { username: string; year: number } }>
    'FinalizeWrapped': EventHandler<{ username: string; year: number }, never>
    'FetchGitHubData': EventHandler<{ username: string; year: number }, { topic: 'calculate-stats'; data: { username: string; year: number } }>
    'CalculateStats': EventHandler<{ username: string; year: number }, { topic: 'generate-achievements'; data: { username: string; year: number } }>
    'ScheduleGenerateWrapped': CronHandler<{ topic: 'fetch-github-data'; data: { username: string; year: number } }>
    'ServeStatic': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, unknown> | ApiResponse<404, { error: string }>, never>
    'ServeStaticJS': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, unknown> | ApiResponse<404, { error: string }>, never>
    'ServeStaticCSS': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, unknown> | ApiResponse<404, { error: string }>, never>
    'ServeFrontend': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, unknown>, never>
    'GetWrapped': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { data: unknown }> | ApiResponse<202, { status: string; message: string; progress?: number }> | ApiResponse<404, { error: string }>, never>
    'GetWrappedStatus': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { username: string; status: 'processing' | 'completed' | 'failed' | 'not_found'; progress?: number; error?: string; startedAt?: string; completedAt?: string }>, never>
    'GetBadge': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, unknown> | ApiResponse<404, { error: string }>, never>
    'GenerateWrapped': ApiRouteHandler<{ year?: number; token?: string }, ApiResponse<200, { status: string; message: string; traceId: string; username: string }> | ApiResponse<404, { error: string }> | ApiResponse<500, { error: string }>, { topic: 'fetch-github-data'; data: { username: string; year: number } }>
  }
    
}